### ISSUE TITLE
SSL configuration always occurs even when connecting to HTTP

### ISSUE THREAD

**Issue by ma2gedev** [lostisland/faraday-net_http#37]
## Description

Even when connecting to HTTP, the initialization of the cert store (`OpenSSL::X509::Store.new`) always occurs. Depending on the environment, this unnecessary initialization process could lead to performance degradation.

In `Faraday::Adapter::NetHttp#configure_ssl`, there is a line `return unless ssl` to return early. However, the `ssl` passed here is an instance of `Faraday::SSLOptions`, so the SSL configuration process always occurs without returning early.

## Environment information

faraday version: 2.10.0
faraday-net_http version: 3.1.0

## Steps to reproduce

Perform a connection to http with the following code:

```
Faraday.new(url: 'http://example.com').get '/'
```

You can confirm that `OpenSSL::X509::Store.new` is always called.

## Expected result

When connecting to HTTP, `OpenSSL::X509::Store.new` should not be called.

## Reference information

It seems that other adapters also check whether it is https scheme when performing the ssl configuration process.

- faraday-httpclient: https://github.com/lostisland/faraday-httpclient/blob/c7d0dfb76a90bc9684aaffbb9497a97764ae2f97/lib/faraday/adapter/httpclient.rb#L28
- faraday-patron: https://github.com/lostisland/faraday-patron/blob/79f8a901a119b45fdc6e587bd0fad599fa43e2b5/lib/faraday/adapter/patron.rb#L10

I think faraday-net_http also need to check whether the scheme is https as a condition for early return.

**Comment by iMacTia** [comment]
Thank you for reporting this issue @ma2gedev, agree it's worth taking a closer look and it should be relatively straightforward to fix.
I'm on holiday until later next month so I won't have time to look into this until then, but a PR would be welcome (and maybe @olleolleolle could review before I'm back).

**Comment by ma2gedev** [comment]
@iMacTia @olleolleolle 

Thank you for your reply. I just created a PR #38 . Could you please review it? Thank you in advance.
