### ISSUE TITLE
Add ciphers to SSL options

### ISSUE THREAD

**Issue by womblep** [lostisland/faraday-net_http#44]
I have hit a server where I needed to pin the ciphers to be able to connect. The server is most certainly badly configured but it is not something I can get changed.

I was able to work around this by monkey-patching Faraday and the Faraday Net::HTTP adapter (Net::HTTP supports ciphers) but I would like to submit patches to make it easier to do.

The Net::HTTP adapter change is adding a new line to the configure_ssl method to set the ciphers on the Net::HTTP instance
Linked to https://github.com/lostisland/faraday/issues/1581

**Comment by iMacTia** [comment]
Addressed in #45
