### ISSUE TITLE
already initialized constant warnings

### ISSUE THREAD

**Issue by rizalmuthi-ap** [lostisland/faraday-net_http#7]
Hey there,
I have updated one of my gems, via `bundle update` and I reckon one of them gem use faraday gem as their dependency. 
And now, everytime I run rspec or migration on my rails app, i have got these warnings
```
/usr/local/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/opt/app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/usr/local/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/opt/app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/usr/local/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/opt/app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here

```

I found out a comment in here: https://github.com/ruby/net-imap/issues/16#issuecomment-803086765 
I wonder whether that will fix this issue.
Thanks

**Comment by iMacTia** [comment]
Hi @rizalmuthi-ap, I've discussed a similar issue in this PR: https://github.com/lostisland/faraday-net_http/pull/5
Long story short, you most probably have a dependency in your Gemfile that has `net-protocol` or similar as a declared dependency. This causes your project to load the gem version of `net-protocol`.
On the other side, in Faraday, we use `net-http` without explicitly declaring it as a dependency. This internally loads the stdlib version of `net-http` for Ruby 2.7 or lower, and the gem version for Ruby 3.0+.

This causes the situation where libraries (like `net-protocol`, in your example) are loaded twice: their gem version and their stdlib version.

I already explained in the PR why I believe Faraday's approach is better, and that other libraries should avoid this kind of explicit dependencies unless they're planning to target only Ruby 3.0+.

I'm sorry I can't really help much more than this.
If you're having a hard time finding the culprit gem, feel free to share your `Gemfile.lock` and I'll have a look to help
